### ISSUE TITLE
Github Actions for Google Cloud Run Job

### ISSUE THREAD

**Issue by noam-solvo** [google-github-actions/deploy-cloudrun#502] opened 2024-04-09 15:42 UTC
### TL;DR

It's easy to use the action for Google Cloud Run Service; it would be great - and more complete - to see another action for deploying a Google Cloud Run Job.

**Comment by sethvargo** [comment] 2024-04-09 23:37
Duplicate of #364

**Closed by sethvargo** 2024-04-09 23:37 UTC
Labels: enhancement
