### ISSUE TITLE
Is it possible to deploy to Cloud Run but as a Job with this workflow?

### ISSUE THREAD

**Issue by digitalghost-dev** [google-github-actions/deploy-cloudrun#424] opened 2023-01-16 07:36 UTC
Referring to this ([create jobs](https://cloud.google.com/run/docs/create-jobs))

**Comment by sethvargo** [comment] 2023-01-16 17:21
Duplicate of https://github.com/google-github-actions/deploy-cloudrun/issues/364

**Closed by sethvargo** 2023-01-16 17:21 UTC
