### ISSUE TITLE
Sandbox selector is not supported

### ISSUE THREAD

**Issue by gabac** [google-github-actions/deploy-cloudrun#36] opened 2021-02-11 06:57 UTC
### TL;DR
The deploy action throws following error message
```Error: The feature 'sandbox selector' is not supported in the declared launch stage on resource cloud-run-demo. The launch stage annotation should be specified at least as BETA. Please visit https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation for in-depth troubleshooting documentation.```

**Expected behavior**
Deployment to Google Cloud Run. It worked before

**Observed behavior**
Error as described on top

### Reproduction

**Action YAML**

```yaml
        - id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/cyril-test-project/cloud-run-demo
          service: cloud-run-demo```
```

**Repository**
not public

**Additional information**
No, I only did some manual deployment through the dashboard in the meantime like change the vCPUs

**Comment by unrealcloud** [comment] 2021-02-11 07:20
Duplicate of https://github.com/google-github-actions/deploy-cloudrun/issues/26, PR https://github.com/google-github-actions/deploy-cloudrun/pull/31 should fix it!

**Comment by averikitsch** [comment] 2021-02-11 21:08
I apologize for the delay. This should be fixed on the main branch or v0.4.0:
```
uses: google-github-actions/deploy-cloudrun@v0.4.0
```

Please reopen if you are still experiencing this issue

**Closed by averikitsch** 2021-02-11 21:08 UTC
Labels: bug

**Comment by gabac** [comment] 2021-02-11 21:28
I can confirm that it works 👍 Thanks a lot for your effort!

**Comment by unrealcloud** [comment] 2021-02-12 02:05
Thank you @averikitsch , I can also confirm that it works! 🎉
